name: Build and Deploy Static Site (Hourly)

on:
  workflow_dispatch:
  schedule:
    # Hourly at minute 5 (UTC)
    - cron: '5 * * * *'
  push:
    branches: [ main, master ]
    paths:
      - 'app/**'
      - 'views/**'
      - 'services/**'
      - 'config/**'
      - 'res/**'
      - 'scripts/build-static.js'
      - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NODE_ENV: production
      # API keys are read from GitHub Secrets. Add these in your repo settings as needed.
      CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
      MESSARI_API_KEY: ${{ secrets.MESSARI_API_KEY }}
      # Optional tuning
      UPDATE_INTERVAL_MINUTES: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build static site
        run: npm run build:static

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: dist

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: 'dist'
          skip_app_build: true
        # If you use SWA routing config, add 'output_location' or 'config_file_location' as needed.

